// Central demo fixtures for AI Radar. Domain contracts live in src/domain/types.ts.
import type {
  ChangeItem,
  Claim,
  Confidence,
  Entity,
  EntityType,
  FollowItem,
  Lang,
  ReadingMode,
  Relation,
  Source,
  Theme,
  TimelineEvent,
} from "@/domain/types";

export type {
  ChangeItem,
  Claim,
  Confidence,
  Entity,
  EntityType,
  FollowItem,
  Lang,
  ReadingMode,
  Relation,
  Source,
  Theme,
  TimelineEvent,
} from "@/domain/types";

export const SOURCES: Source[] = [
  {
    id: "s-openai-gpt5",
    title: { zh: "OpenAI 发布 GPT-5（演示）", en: "OpenAI announces GPT-5 (demo)" },
    url: "https://openai.com/",
    publisher: "OpenAI",
    publishedAt: "2026-07-12",
    collectedAt: "2026-07-12",
    verifiedAt: "2026-07-13",
    type: "official",
  },
  {
    id: "s-anthropic-claude",
    title: { zh: "Anthropic Claude 4.5 系统卡", en: "Anthropic Claude 4.5 system card" },
    url: "https://www.anthropic.com/",
    publisher: "Anthropic",
    publishedAt: "2026-06-20",
    collectedAt: "2026-06-20",
    verifiedAt: "2026-06-21",
    type: "official",
  },
  {
    id: "s-deepseek-r2",
    title: { zh: "DeepSeek R2 技术报告", en: "DeepSeek R2 technical report" },
    url: "https://arxiv.org/",
    publisher: "arXiv",
    publishedAt: "2026-05-30",
    collectedAt: "2026-05-30",
    type: "paper",
  },
  {
    id: "s-community-rumor",
    title: {
      zh: "社区讨论：GPT-5 上下文窗口传闻",
      en: "Community rumor: GPT-5 context window",
    },
    url: "https://news.ycombinator.com/",
    publisher: "Hacker News",
    publishedAt: "2026-07-10",
    collectedAt: "2026-07-10",
    type: "community",
  },
  {
    id: "s-swebench",
    title: { zh: "SWE-bench Verified 排行榜", en: "SWE-bench Verified leaderboard" },
    url: "https://www.swebench.com/",
    publisher: "SWE-bench",
    publishedAt: "2026-07-15",
    collectedAt: "2026-07-15",
    verifiedAt: "2026-07-16",
    type: "benchmark",
  },
  {
    id: "s-google-gemini",
    title: { zh: "Google Gemini 2.5 Pro 更新", en: "Google Gemini 2.5 Pro update" },
    url: "https://deepmind.google/",
    publisher: "Google DeepMind",
    publishedAt: "2026-07-05",
    collectedAt: "2026-07-05",
    verifiedAt: "2026-07-06",
    type: "official",
  },
];

export const ENTITIES: Entity[] = [
  {
    id: "e-gpt",
    type: "model",
    slug: "gpt",
    name: { zh: "GPT 系列", en: "GPT family" },
    aliases: ["ChatGPT", "GPT-4", "GPT-5"],
    vendor: "OpenAI",
    origin: { zh: "美国", en: "United States" },
    summary: {
      zh: "OpenAI 推出的通用大型语言模型家族，覆盖对话、代码、推理与多模态能力，是当前商业化最成熟的闭源前沿模型之一。",
      en: "OpenAI's general-purpose LLM family covering chat, code, reasoning and multimodal capabilities; among the most commercially mature closed frontier models today.",
    },
    status: "active",
    tags: ["LLM", "闭源", "多模态", "推理"],
    latestVersion: "GPT-5",
    firstReleasedAt: "2018-06-11",
    lastUpdatedAt: "2026-07-12",
    capabilities: [
      { zh: "长上下文推理", en: "Long-context reasoning", confidence: "verified" },
      { zh: "图像与语音多模态", en: "Image & audio multimodality", confidence: "verified" },
      { zh: "Agent 工具调用", en: "Agentic tool use", confidence: "verified" },
      {
        zh: "1M token 上下文（未核验）",
        en: "1M token context (unverified)",
        confidence: "unverified",
      },
    ],
    metrics: [
      {
        name: "MMLU",
        value: "91.2",
        benchmark: "MMLU-Pro",
        date: "2026-07-12",
        confidence: "verified",
      },
      {
        name: "SWE-bench Verified",
        value: "62.4%",
        benchmark: "SWE-bench Verified",
        date: "2026-07-15",
        confidence: "verified",
      },
      {
        name: "GPQA Diamond",
        value: "84.1",
        benchmark: "GPQA",
        date: "2026-07-12",
        confidence: "inferred",
      },
    ],
  },
  {
    id: "e-gpt-4o",
    type: "model",
    slug: "gpt-4o",
    name: { zh: "GPT-4o", en: "GPT-4o" },
    aliases: ["GPT-4 Omni"],
    vendor: "OpenAI",
    origin: { zh: "美国", en: "United States" },
    summary: {
      zh: "GPT 系列的原生多模态版本，将文本、图像与语音整合进单一模型，重点改善实时交互速度与成本。",
      en: "A native multimodal GPT release unifying text, image, and audio, with an emphasis on latency and cost.",
    },
    status: "active",
    tags: ["具体版本", "GPT版本", "多模态", "低延迟"],
    latestVersion: "gpt-4o-2024-08-06",
    firstReleasedAt: "2024-05-13",
    lastUpdatedAt: "2024-08-06",
    specs: {
      contextWindow: "128K tokens",
      inputPrice: "$2.50 / 1M tokens",
      outputPrice: "$10.00 / 1M tokens",
      modalities: "文本 · 图像 · 音频",
      toolUse: "函数调用 · 结构化输出",
      availability: "API · ChatGPT",
    },
    capabilities: [
      { zh: "原生语音对话", en: "Native voice interaction", confidence: "verified" },
      { zh: "图像理解与生成协作", en: "Visual understanding", confidence: "verified" },
      { zh: "低延迟工具调用", en: "Low-latency tool use", confidence: "verified" },
    ],
  },
  {
    id: "e-gpt-45",
    type: "model",
    slug: "gpt-4-5",
    name: { zh: "GPT-4.5 Preview", en: "GPT-4.5 Preview" },
    vendor: "OpenAI",
    origin: { zh: "美国", en: "United States" },
    summary: {
      zh: "面向自然对话、知识广度与创意写作的过渡版本，推理方式更自然，但 API 成本明显高于 GPT-4o。",
      en: "A transitional release focused on natural conversation, broad knowledge, and writing quality, at a substantially higher API price than GPT-4o.",
    },
    status: "active",
    tags: ["具体版本", "GPT版本", "写作", "高成本"],
    latestVersion: "gpt-4.5-preview",
    firstReleasedAt: "2025-02-27",
    lastUpdatedAt: "2025-07-14",
    specs: {
      contextWindow: "128K tokens",
      inputPrice: "$75.00 / 1M tokens",
      outputPrice: "$150.00 / 1M tokens",
      modalities: "文本 · 图像",
      toolUse: "函数调用",
      availability: "API · ChatGPT Pro",
    },
    capabilities: [
      { zh: "自然对话与写作", en: "Natural conversation and writing", confidence: "verified" },
      { zh: "更低幻觉率", en: "Lower hallucination rate", confidence: "inferred" },
      { zh: "复杂指令遵循", en: "Complex instruction following", confidence: "verified" },
    ],
  },
  {
    id: "e-gpt-5",
    type: "model",
    slug: "gpt-5",
    name: { zh: "GPT-5", en: "GPT-5" },
    vendor: "OpenAI",
    origin: { zh: "美国", en: "United States" },
    summary: {
      zh: "GPT 系列当前演示旗舰版本，统一快速响应与深度推理，强化代码、长上下文、多模态与 Agent 工具调用。",
      en: "The current demo flagship GPT release, unifying fast responses and deep reasoning with stronger code, long context, multimodality, and agentic tool use.",
    },
    status: "active",
    tags: ["具体版本", "GPT版本", "推理", "Agent", "多模态"],
    latestVersion: "gpt-5-2026-07-12",
    firstReleasedAt: "2026-07-12",
    lastUpdatedAt: "2026-07-15",
    specs: {
      contextWindow: "256K tokens（1M 未核验）",
      inputPrice: "$0.50 / 1M tokens（演示）",
      outputPrice: "$1.50 / 1M tokens（演示）",
      modalities: "文本 · 图像 · 音频 · 视频",
      toolUse: "并行工具调用 · Agent 编排",
      availability: "API · ChatGPT",
    },
    capabilities: [
      { zh: "自适应深度推理", en: "Adaptive deep reasoning", confidence: "verified" },
      { zh: "并行 Agent 工具调用", en: "Parallel agentic tool use", confidence: "verified" },
      { zh: "长视频与多模态理解", en: "Long-video multimodality", confidence: "verified" },
    ],
    metrics: [
      {
        name: "SWE-bench Verified",
        value: "62.4%",
        benchmark: "SWE-bench Verified",
        date: "2026-07-15",
        confidence: "verified",
      },
      {
        name: "GPQA Diamond",
        value: "84.1",
        benchmark: "GPQA",
        date: "2026-07-12",
        confidence: "inferred",
      },
    ],
  },
  {
    id: "e-claude",
    type: "model",
    slug: "claude",
    name: { zh: "Claude 系列", en: "Claude family" },
    vendor: "Anthropic",
    origin: { zh: "美国", en: "United States" },
    summary: {
      zh: "Anthropic 推出的以安全对齐与长文本理解见长的大型语言模型家族，Claude 4.5 强化了代码与 Agent 场景。",
      en: "Anthropic's LLM family known for safety alignment and long-context understanding; Claude 4.5 focuses on code and agentic use cases.",
    },
    status: "active",
    tags: ["LLM", "闭源", "长文本", "对齐"],
    latestVersion: "Claude 4.5 Sonnet",
    firstReleasedAt: "2023-03-14",
    lastUpdatedAt: "2026-06-20",
  },
  {
    id: "e-claude-35",
    type: "model",
    slug: "claude-3-5-sonnet",
    name: { zh: "Claude 3.5 Sonnet", en: "Claude 3.5 Sonnet" },
    vendor: "Anthropic",
    origin: { zh: "美国", en: "United States" },
    summary: {
      zh: "Claude 系列的重要效率版本，强化代码、视觉理解与 Artifacts 交互，在性能和价格之间取得平衡。",
      en: "A major efficiency release adding stronger code, vision, and Artifacts while balancing capability and price.",
    },
    status: "active",
    tags: ["具体版本", "Claude版本", "代码", "Artifacts"],
    latestVersion: "claude-3-5-sonnet-20241022",
    firstReleasedAt: "2024-06-20",
    lastUpdatedAt: "2024-10-22",
    specs: {
      contextWindow: "200K tokens",
      inputPrice: "$3.00 / 1M tokens",
      outputPrice: "$15.00 / 1M tokens",
      modalities: "文本 · 图像",
      toolUse: "工具调用 · Computer use",
      availability: "API · Claude",
    },
    capabilities: [
      { zh: "代码生成与重构", en: "Code generation and refactoring", confidence: "verified" },
      { zh: "Artifacts 协作", en: "Artifacts workflow", confidence: "verified" },
    ],
  },
  {
    id: "e-claude-4",
    type: "model",
    slug: "claude-4-sonnet",
    name: { zh: "Claude 4 Sonnet", en: "Claude 4 Sonnet" },
    vendor: "Anthropic",
    origin: { zh: "美国", en: "United States" },
    summary: {
      zh: "面向长时间 Agent 任务与复杂代码工程的版本，增加扩展思考和更稳定的多步骤工具调用。",
      en: "A release for long-running agent tasks and complex software engineering, adding extended thinking and steadier multi-step tool use.",
    },
    status: "active",
    tags: ["具体版本", "Claude版本", "Agent", "扩展思考"],
    latestVersion: "claude-4-sonnet-20250522",
    firstReleasedAt: "2025-05-22",
    lastUpdatedAt: "2025-05-22",
    specs: {
      contextWindow: "200K tokens",
      inputPrice: "$3.00 / 1M tokens",
      outputPrice: "$15.00 / 1M tokens",
      modalities: "文本 · 图像",
      toolUse: "并行工具调用 · Computer use",
      availability: "API · Claude",
    },
    capabilities: [
      { zh: "扩展思考", en: "Extended thinking", confidence: "verified" },
      { zh: "长时间 Agent 任务", en: "Long-running agent tasks", confidence: "verified" },
    ],
  },
  {
    id: "e-claude-45",
    type: "model",
    slug: "claude-4-5-sonnet",
    name: { zh: "Claude 4.5 Sonnet", en: "Claude 4.5 Sonnet" },
    vendor: "Anthropic",
    origin: { zh: "美国", en: "United States" },
    summary: {
      zh: "Claude 系列当前演示旗舰版本，进一步提升代码、长文档和 Agent 稳定性，并降低安全策略的误拒率。",
      en: "The current demo flagship Claude release with stronger code, long-document work, and agent reliability, plus fewer false safety refusals.",
    },
    status: "active",
    tags: ["具体版本", "Claude版本", "代码", "Agent", "长文本"],
    latestVersion: "claude-4-5-sonnet-20260620",
    firstReleasedAt: "2026-06-20",
    lastUpdatedAt: "2026-06-20",
    specs: {
      contextWindow: "2M tokens（预览）",
      inputPrice: "$3.00 / 1M tokens（演示）",
      outputPrice: "$15.00 / 1M tokens（演示）",
      modalities: "文本 · 图像",
      toolUse: "并行工具调用 · MCP · Computer use",
      availability: "API · Claude",
    },
    capabilities: [
      { zh: "超长文档理解", en: "Ultra-long document understanding", confidence: "verified" },
      { zh: "稳定的代码 Agent", en: "Reliable coding agents", confidence: "verified" },
      { zh: "MCP 工具生态", en: "MCP tool ecosystem", confidence: "verified" },
    ],
    metrics: [
      {
        name: "Safety false refusal",
        value: "-18%",
        benchmark: "Anthropic safety eval",
        date: "2026-06-20",
        confidence: "verified",
      },
    ],
  },
  {
    id: "e-gemini",
    type: "model",
    slug: "gemini",
    name: { zh: "Gemini 系列", en: "Gemini family" },
    vendor: "Google DeepMind",
    origin: { zh: "美国", en: "United States" },
    summary: {
      zh: "Google DeepMind 的多模态旗舰模型家族，原生支持文本、图像、音频与视频输入。",
      en: "Google DeepMind's multimodal flagship family with native text, image, audio and video inputs.",
    },
    status: "active",
    tags: ["LLM", "闭源", "多模态", "长上下文"],
    latestVersion: "Gemini 2.5 Pro",
    firstReleasedAt: "2023-12-06",
    lastUpdatedAt: "2026-07-05",
  },
  {
    id: "e-deepseek",
    type: "model",
    slug: "deepseek",
    name: { zh: "DeepSeek 系列", en: "DeepSeek family" },
    vendor: "深度求索",
    origin: { zh: "中国", en: "China" },
    summary: {
      zh: "国产开源前沿模型代表，DeepSeek R2 主打推理与代码，训练与推理成本大幅低于同代闭源模型。",
      en: "Leading Chinese open-source frontier models; DeepSeek R2 focuses on reasoning and code with markedly lower training & inference cost.",
    },
    status: "active",
    tags: ["LLM", "开源", "推理", "中国"],
    latestVersion: "DeepSeek R2",
    firstReleasedAt: "2023-11-29",
    lastUpdatedAt: "2026-05-30",
  },
  {
    id: "e-qwen",
    type: "model",
    slug: "qwen",
    name: { zh: "通义千问 Qwen", en: "Qwen" },
    vendor: "阿里巴巴",
    origin: { zh: "中国", en: "China" },
    summary: {
      zh: "阿里巴巴推出的开源模型家族，覆盖对话、代码、视觉与音频，具备完整的开源权重生态。",
      en: "Alibaba's open-weight model family covering chat, code, vision and audio with a complete open ecosystem.",
    },
    status: "active",
    tags: ["LLM", "开源", "多模态", "中国"],
    latestVersion: "Qwen3-Max",
    firstReleasedAt: "2023-08-03",
    lastUpdatedAt: "2026-07-01",
  },
  {
    id: "e-kimi",
    type: "model",
    slug: "kimi",
    name: { zh: "Kimi", en: "Kimi" },
    vendor: "月之暗面",
    origin: { zh: "中国", en: "China" },
    summary: {
      zh: "月之暗面 Kimi 以超长上下文与深度阅读见长，主打个人研究与文档理解。",
      en: "Moonshot's Kimi is known for ultra-long context and deep-reading workflows for personal research.",
    },
    status: "active",
    tags: ["LLM", "长上下文", "阅读"],
    latestVersion: "Kimi K2",
    firstReleasedAt: "2023-10-09",
    lastUpdatedAt: "2026-06-18",
  },
  {
    id: "e-doubao",
    type: "model",
    slug: "doubao",
    name: { zh: "豆包 Doubao", en: "Doubao" },
    vendor: "字节跳动",
    origin: { zh: "中国", en: "China" },
    summary: {
      zh: "字节跳动的豆包模型家族，服务于抖音、剪映等 C 端产品，主打低成本与高并发。",
      en: "ByteDance's Doubao family powering consumer products like Douyin & CapCut, focused on cost and throughput.",
    },
    status: "active",
    tags: ["LLM", "C端", "低成本"],
    latestVersion: "Doubao 1.5 Pro",
    firstReleasedAt: "2024-05-15",
    lastUpdatedAt: "2026-06-25",
  },
  {
    id: "e-ernie",
    type: "model",
    slug: "ernie",
    name: { zh: "文心一言 ERNIE Bot", en: "ERNIE Bot" },
    vendor: "百度",
    origin: { zh: "中国", en: "China" },
    summary: {
      zh: "百度文心系列模型，2026 年升级为 ERNIE 5，强化了搜索增强与行业解决方案能力。",
      en: "Baidu's ERNIE family, upgraded to ERNIE 5 in 2026 with search-augmented and industry solutions.",
    },
    status: "active",
    tags: ["LLM", "搜索", "行业"],
    latestVersion: "ERNIE 5",
    firstReleasedAt: "2023-03-16",
    lastUpdatedAt: "2026-04-10",
  },
  {
    id: "e-openai",
    type: "company",
    slug: "openai",
    name: { zh: "OpenAI", en: "OpenAI" },
    summary: {
      zh: "总部位于旧金山的 AI 研究与产品公司，GPT 系列与 ChatGPT 的开发者。",
      en: "SF-based AI research and product company; developer of the GPT family and ChatGPT.",
    },
    status: "active",
    tags: ["公司", "闭源"],
    lastUpdatedAt: "2026-07-12",
  },
  {
    id: "e-anthropic",
    type: "company",
    slug: "anthropic",
    name: { zh: "Anthropic", en: "Anthropic" },
    summary: {
      zh: "以安全对齐为核心方向的 AI 公司，Claude 系列的开发者。",
      en: "Safety-focused AI company; developer of Claude.",
    },
    status: "active",
    tags: ["公司", "对齐"],
    lastUpdatedAt: "2026-06-20",
  },
  {
    id: "e-langchain",
    type: "framework",
    slug: "langchain",
    name: { zh: "LangChain", en: "LangChain" },
    summary: {
      zh: "面向 LLM 应用编排的开源框架，覆盖链、工具、Agent 与检索增强。",
      en: "Open-source framework for LLM app orchestration: chains, tools, agents and RAG.",
    },
    status: "active",
    tags: ["框架", "Agent", "RAG"],
    latestVersion: "0.3",
    lastUpdatedAt: "2026-07-01",
  },
  {
    id: "e-swebench",
    type: "benchmark",
    slug: "swe-bench",
    name: { zh: "SWE-bench Verified", en: "SWE-bench Verified" },
    summary: {
      zh: "针对真实 GitHub Issue 的代码修复评测，衡量模型端到端解决工程问题的能力。",
      en: "Real-world GitHub issue coding benchmark measuring end-to-end engineering task solving.",
    },
    status: "active",
    tags: ["评测", "代码"],
    lastUpdatedAt: "2026-07-15",
  },
  {
    id: "e-mmlu",
    type: "benchmark",
    slug: "mmlu-pro",
    name: { zh: "MMLU-Pro", en: "MMLU-Pro" },
    summary: {
      zh: "覆盖 57 个学科的多任务语言理解评测的强化版，更抗污染。",
      en: "Harder, contamination-resistant version of the 57-subject multitask language benchmark.",
    },
    status: "active",
    tags: ["评测", "通用"],
    lastUpdatedAt: "2026-05-20",
  },
  {
    id: "e-transformer-paper",
    type: "paper",
    slug: "attention-is-all-you-need",
    name: { zh: "Attention Is All You Need", en: "Attention Is All You Need" },
    summary: {
      zh: "提出 Transformer 架构的开山论文，奠定了现代大模型的基础。",
      en: "Seminal paper introducing the Transformer architecture behind modern LLMs.",
    },
    status: "active",
    tags: ["论文", "架构"],
    firstReleasedAt: "2017-06-12",
    lastUpdatedAt: "2017-06-12",
  },
  {
    id: "e-mcp",
    type: "framework",
    slug: "mcp",
    name: { zh: "Model Context Protocol", en: "Model Context Protocol" },
    summary: {
      zh: "由 Anthropic 提出的模型上下文协议，定义模型与外部工具、数据源交互的开放接口。",
      en: "Anthropic-proposed open protocol for how models talk to external tools & data sources.",
    },
    status: "active",
    tags: ["协议", "Agent"],
    latestVersion: "1.0",
    lastUpdatedAt: "2026-06-05",
  },
  {
    id: "e-cursor",
    type: "application",
    slug: "cursor",
    name: { zh: "Cursor", en: "Cursor" },
    summary: {
      zh: "深度集成大模型的代码编辑器，是 Agent 编码的代表产品之一。",
      en: "AI-native code editor and one of the flagship agentic coding products.",
    },
    status: "active",
    tags: ["应用", "代码"],
    lastUpdatedAt: "2026-07-10",
  },
];

export const CLAIMS: Claim[] = [
  {
    id: "c-gpt5-swe",
    text: {
      zh: "GPT-5 在 SWE-bench Verified 上取得 62.4% 的通过率。",
      en: "GPT-5 achieves 62.4% pass rate on SWE-bench Verified.",
      technical: {
        zh: "在 SWE-bench Verified 500 题子集上，GPT-5 (2026-07-12 发布版) 单次尝试的解决率为 62.4%。",
        en: "On the 500-task SWE-bench Verified subset, GPT-5 (2026-07-12 release) solves 62.4% in a single attempt.",
      },
    },
    confidence: "verified",
    sourceIds: ["s-openai-gpt5", "s-swebench"],
    updatedAt: "2026-07-15",
  },
  {
    id: "c-gpt5-1m",
    text: {
      zh: "GPT-5 支持 1,000,000 token 的上下文窗口。",
      en: "GPT-5 supports a 1,000,000-token context window.",
    },
    confidence: "unverified",
    sourceIds: ["s-community-rumor"],
    updatedAt: "2026-07-10",
  },
  {
    id: "c-claude-align",
    text: {
      zh: "Claude 4.5 在 Anthropic 官方安全评估中拒绝率下降 18%，同时保持有害请求识别率。",
      en: "Claude 4.5 reduces false refusals by 18% while retaining harmful-request detection per Anthropic's evals.",
    },
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
    updatedAt: "2026-06-20",
  },
  {
    id: "c-deepseek-cost",
    text: {
      zh: "DeepSeek R2 的推理成本约为同代闭源模型的 1/10。",
      en: "DeepSeek R2 inference cost is roughly 1/10 of comparable closed models.",
    },
    confidence: "inferred",
    sourceIds: ["s-deepseek-r2"],
    updatedAt: "2026-05-30",
  },
  {
    id: "c-gemini-video",
    text: {
      zh: "Gemini 2.5 Pro 原生支持 2 小时长视频输入。",
      en: "Gemini 2.5 Pro natively supports up to 2-hour video inputs.",
    },
    confidence: "verified",
    sourceIds: ["s-google-gemini"],
    updatedAt: "2026-07-05",
  },
];

export const TIMELINE: Record<string, TimelineEvent[]> = {
  "e-gpt": [
    {
      id: "t-gpt-1",
      date: "2018-06-11",
      title: { zh: "GPT-1 发布", en: "GPT-1 released" },
      summary: {
        zh: "1.17 亿参数，验证“通用预训练 + 任务微调”路线；以文本理解为主，尚无公开 API 定价。",
        en: "117M parameters validated general pre-training plus task fine-tuning; text-only and no public API pricing.",
      },
      kind: "release",
      sourceIds: ["s-openai-gpt5"],
      confidence: "verified",
    },
    {
      id: "t-gpt-2",
      date: "2020-05-28",
      title: { zh: "GPT-3 发布", en: "GPT-3 released" },
      summary: {
        zh: "扩展到 1750 亿参数，重点变化是无需微调的 few-shot 提示能力，并开始形成按 token 计费的 API 产品形态。",
        en: "Scaled to 175B parameters, introduced strong few-shot prompting and established token-priced API access.",
      },
      kind: "release",
      sourceIds: ["s-openai-gpt5"],
      confidence: "verified",
    },
    {
      id: "t-gpt-3",
      date: "2022-11-30",
      title: { zh: "ChatGPT 上线", en: "ChatGPT launched" },
      summary: {
        zh: "将指令微调与对话界面结合，5 天内突破百万用户；模型能力从 API 组件变成普通用户可直接使用的产品。",
        en: "Combined instruction tuning with a chat UI, reaching 1M users in five days and turning model APIs into a consumer product.",
      },
      kind: "release",
      sourceIds: ["s-openai-gpt5"],
      confidence: "verified",
    },
    {
      id: "t-gpt-4",
      date: "2023-03-14",
      title: { zh: "GPT-4 发布", en: "GPT-4 released" },
      summary: {
        zh: "新增图像输入并显著提高复杂推理；首发提供 8K / 32K 上下文，演示归一化 API 价格约为输入 $30、输出 $60 / 百万 tokens。",
        en: "Added image input and stronger reasoning, with 8K/32K context; normalized launch pricing was about $30 input and $60 output per 1M tokens.",
      },
      kind: "release",
      sourceIds: ["s-openai-gpt5"],
      confidence: "verified",
    },
    {
      id: "t-gpt-4o",
      date: "2024-05-13",
      title: { zh: "GPT-4o：原生全模态与成本下降", en: "GPT-4o: native omni and lower cost" },
      summary: {
        zh: "文本、图像与音频走向原生统一处理，延迟明显降低；128K 上下文，演示价格为输入 $2.5、输出 $10 / 百万 tokens。",
        en: "Unified text, image and audio processing with lower latency; 128K context and demo pricing of $2.5 input / $10 output per 1M tokens.",
      },
      kind: "release",
      sourceIds: ["s-openai-gpt5"],
      confidence: "verified",
    },
    {
      id: "t-gpt-45",
      date: "2025-02-27",
      title: { zh: "GPT-4.5：知识与自然表达增强", en: "GPT-4.5: knowledge and natural writing" },
      summary: {
        zh: "重点改善知识覆盖、写作自然度与意图理解，而非单纯追求推理速度；128K 上下文，演示价格为输入 $75、输出 $150 / 百万 tokens。",
        en: "Focused on knowledge, natural writing and intent understanding rather than raw reasoning speed; 128K context and demo pricing of $75/$150.",
      },
      kind: "release",
      sourceIds: ["s-openai-gpt5"],
      confidence: "verified",
    },
    {
      id: "t-gpt-5",
      date: "2026-07-12",
      title: { zh: "GPT-5 发布（演示）", en: "GPT-5 released (demo)" },
      summary: {
        zh: "统一推理、多模态与 Agent 工具调用；上下文扩至 256K、支持 8 个并行工具，演示价格为输入 $0.5、输出 $1.5 / 百万 tokens。",
        en: "Unified reasoning, multimodality and agentic tool use; 256K context, eight parallel tools and demo pricing of $0.5/$1.5.",
      },
      kind: "release",
      sourceIds: ["s-openai-gpt5", "s-swebench"],
      confidence: "verified",
    },
    {
      id: "t-gpt-rumor",
      date: "2026-07-10",
      title: { zh: "社区传闻：1M 上下文", en: "Community rumor: 1M context" },
      summary: {
        zh: "多个开发者社区讨论 GPT-5 可能支持 1M token 上下文，官方未确认。",
        en: "Developers speculate 1M context for GPT-5; not officially confirmed.",
      },
      kind: "update",
      sourceIds: ["s-community-rumor"],
      confidence: "unverified",
    },
  ],
  "e-claude": [
    {
      id: "t-c-1",
      date: "2023-03-14",
      title: { zh: "Claude 首版发布", en: "Claude 1 released" },
      summary: {
        zh: "Anthropic 首个对外模型产品，以长文本、可靠对话和 Constitutional AI 路线为主要差异点。",
        en: "Anthropic's first public model, differentiated by long-form dialogue and Constitutional AI.",
      },
      kind: "release",
      sourceIds: ["s-anthropic-claude"],
      confidence: "verified",
    },
    {
      id: "t-c-35",
      date: "2024-06-20",
      title: {
        zh: "Claude 3.5 Sonnet：代码与性价比跃升",
        en: "Claude 3.5 Sonnet: coding and value",
      },
      summary: {
        zh: "在 200K 上下文中强化代码、视觉理解和工具调用；演示价格为输入 $3、输出 $15 / 百万 tokens。",
        en: "Improved coding, vision and tool use in a 200K context window; demo pricing of $3/$15 per 1M tokens.",
      },
      kind: "release",
      sourceIds: ["s-anthropic-claude"],
      confidence: "verified",
    },
    {
      id: "t-c-4",
      date: "2025-05-22",
      title: {
        zh: "Claude 4 Sonnet：面向 Agent 的持续执行",
        en: "Claude 4 Sonnet: sustained agent execution",
      },
      summary: {
        zh: "增强多步骤 Agent、代码仓库理解与并行工具调用；200K 上下文，演示价格维持输入 $3、输出 $15。",
        en: "Added stronger multi-step agents, repository understanding and parallel tools; 200K context at demo pricing of $3/$15.",
      },
      kind: "release",
      sourceIds: ["s-anthropic-claude"],
      confidence: "verified",
    },
    {
      id: "t-c-2",
      date: "2026-06-20",
      title: { zh: "Claude 4.5 Sonnet 发布", en: "Claude 4.5 Sonnet released" },
      summary: {
        zh: "上下文扩至 2M（预览），强化 Agent 与代码能力并降低误拒；演示价格为输入 $3、输出 $15 / 百万 tokens。",
        en: "Expanded to a 2M context preview with better agents, coding and fewer false refusals; demo pricing of $3/$15.",
      },
      kind: "release",
      sourceIds: ["s-anthropic-claude"],
      confidence: "verified",
    },
  ],
  "e-gpt-4o": [],
  "e-gpt-45": [],
  "e-gpt-5": [],
  "e-claude-35": [],
  "e-claude-4": [],
  "e-claude-45": [],
};

TIMELINE["e-gpt-4o"] = TIMELINE["e-gpt"].filter((event) => event.id === "t-gpt-4o");
TIMELINE["e-gpt-45"] = TIMELINE["e-gpt"].filter((event) => event.id === "t-gpt-45");
TIMELINE["e-gpt-5"] = TIMELINE["e-gpt"].filter((event) => event.id === "t-gpt-5");
TIMELINE["e-claude-35"] = TIMELINE["e-claude"].filter((event) => event.id === "t-c-35");
TIMELINE["e-claude-4"] = TIMELINE["e-claude"].filter((event) => event.id === "t-c-4");
TIMELINE["e-claude-45"] = TIMELINE["e-claude"].filter((event) => event.id === "t-c-2");

export const RELATIONS: Relation[] = [
  {
    id: "r1",
    fromId: "e-gpt",
    toId: "e-openai",
    kind: "developed-by",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r2",
    fromId: "e-claude",
    toId: "e-anthropic",
    kind: "developed-by",
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
  },
  {
    id: "r3",
    fromId: "e-gpt",
    toId: "e-claude",
    kind: "competes-with",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r4",
    fromId: "e-gpt",
    toId: "e-gemini",
    kind: "competes-with",
    confidence: "verified",
    sourceIds: ["s-google-gemini"],
  },
  {
    id: "r5",
    fromId: "e-gpt",
    toId: "e-deepseek",
    kind: "competes-with",
    confidence: "inferred",
    sourceIds: ["s-deepseek-r2"],
  },
  {
    id: "r6",
    fromId: "e-gpt",
    toId: "e-swebench",
    kind: "benchmarked-on",
    confidence: "verified",
    sourceIds: ["s-swebench"],
  },
  {
    id: "r7",
    fromId: "e-gpt",
    toId: "e-mmlu",
    kind: "benchmarked-on",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r8",
    fromId: "e-gpt",
    toId: "e-transformer-paper",
    kind: "based-on",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r9",
    fromId: "e-cursor",
    toId: "e-gpt",
    kind: "uses",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r10",
    fromId: "e-mcp",
    toId: "e-anthropic",
    kind: "developed-by",
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
  },
  {
    id: "r11",
    fromId: "e-langchain",
    toId: "e-gpt",
    kind: "uses",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r12",
    fromId: "e-langchain",
    toId: "e-claude",
    kind: "uses",
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
  },
  {
    id: "r13",
    fromId: "e-claude",
    toId: "e-swebench",
    kind: "benchmarked-on",
    confidence: "verified",
    sourceIds: ["s-swebench"],
  },
  {
    id: "r14",
    fromId: "e-deepseek",
    toId: "e-transformer-paper",
    kind: "based-on",
    confidence: "verified",
    sourceIds: ["s-deepseek-r2"],
  },
  {
    id: "r15",
    fromId: "e-qwen",
    toId: "e-mmlu",
    kind: "benchmarked-on",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r16",
    fromId: "e-gpt-4o",
    toId: "e-gpt",
    kind: "part-of",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r17",
    fromId: "e-gpt-45",
    toId: "e-gpt",
    kind: "part-of",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r18",
    fromId: "e-gpt-5",
    toId: "e-gpt",
    kind: "part-of",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r19",
    fromId: "e-gpt-45",
    toId: "e-gpt-4o",
    kind: "successor-of",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r20",
    fromId: "e-gpt-5",
    toId: "e-gpt-45",
    kind: "successor-of",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r21",
    fromId: "e-gpt-5",
    toId: "e-openai",
    kind: "developed-by",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5"],
  },
  {
    id: "r22",
    fromId: "e-gpt-5",
    toId: "e-swebench",
    kind: "benchmarked-on",
    confidence: "verified",
    sourceIds: ["s-swebench"],
  },
  {
    id: "r23",
    fromId: "e-claude-35",
    toId: "e-claude",
    kind: "part-of",
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
  },
  {
    id: "r24",
    fromId: "e-claude-4",
    toId: "e-claude",
    kind: "part-of",
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
  },
  {
    id: "r25",
    fromId: "e-claude-45",
    toId: "e-claude",
    kind: "part-of",
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
  },
  {
    id: "r26",
    fromId: "e-claude-4",
    toId: "e-claude-35",
    kind: "successor-of",
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
  },
  {
    id: "r27",
    fromId: "e-claude-45",
    toId: "e-claude-4",
    kind: "successor-of",
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
  },
  {
    id: "r28",
    fromId: "e-claude-45",
    toId: "e-anthropic",
    kind: "developed-by",
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
  },
  {
    id: "r29",
    fromId: "e-claude-45",
    toId: "e-mcp",
    kind: "uses",
    confidence: "verified",
    sourceIds: ["s-anthropic-claude"],
  },
  {
    id: "r30",
    fromId: "e-gpt-5",
    toId: "e-claude-45",
    kind: "competes-with",
    confidence: "verified",
    sourceIds: ["s-openai-gpt5", "s-anthropic-claude"],
  },
];

export const RECENT_CHANGES: ChangeItem[] = [
  {
    id: "ch1",
    entityId: "e-gpt",
    date: "2026-07-15",
    summary: {
      zh: "GPT-5 在 SWE-bench Verified 上刷新记录（62.4%）。",
      en: "GPT-5 sets new SWE-bench Verified record (62.4%).",
    },
    kind: "benchmark",
    confidence: "verified",
  },
  {
    id: "ch2",
    entityId: "e-claude",
    date: "2026-07-14",
    summary: {
      zh: "Claude 4.5 新增 200 万 token 长文档预览。",
      en: "Claude 4.5 adds 2M-token long doc preview.",
    },
    kind: "updated",
    confidence: "verified",
  },
  {
    id: "ch3",
    entityId: "e-deepseek",
    date: "2026-07-13",
    summary: {
      zh: "DeepSeek R2 权重上传 Hugging Face，社区开始复现基准。",
      en: "DeepSeek R2 weights on Hugging Face; community starts reproducing benchmarks.",
    },
    kind: "new",
    confidence: "verified",
  },
  {
    id: "ch9",
    entityId: "e-deepseek",
    date: "2026-07-11",
    summary: {
      zh: "DeepSeek R2 API 输入价格下调 30%，上下文窗口扩展至 256K。",
      en: "DeepSeek R2 API input pricing drops 30% and context expands to 256K.",
    },
    kind: "updated",
    confidence: "inferred",
    sourceIds: ["s-deepseek-r2"],
  },
  {
    id: "ch4",
    entityId: "e-gemini",
    date: "2026-07-12",
    summary: {
      zh: "Gemini 2.5 Pro 视频输入延长到 2 小时。",
      en: "Gemini 2.5 Pro video input extended to 2h.",
    },
    kind: "updated",
    confidence: "verified",
  },
  {
    id: "ch5",
    entityId: "e-gpt",
    date: "2026-07-10",
    summary: {
      zh: "社区传闻 GPT-5 上下文可达 1M，官方未确认。",
      en: "Community rumor: GPT-5 context up to 1M; not confirmed.",
    },
    kind: "rumor",
    confidence: "unverified",
  },
  {
    id: "ch6",
    entityId: "e-mcp",
    date: "2026-07-08",
    summary: {
      zh: "MCP 1.0 稳定版发布，主流 IDE 已集成。",
      en: "MCP 1.0 stable released; major IDEs integrated.",
    },
    kind: "new",
    confidence: "verified",
  },
  {
    id: "ch7",
    entityId: "e-qwen",
    date: "2026-07-07",
    summary: { zh: "Qwen3-Max 开源 480B 参数版本。", en: "Qwen3-Max open-sources 480B variant." },
    kind: "new",
    confidence: "verified",
  },
  {
    id: "ch8",
    entityId: "e-cursor",
    date: "2026-07-06",
    summary: {
      zh: "Cursor 支持自定义 Agent 编排。",
      en: "Cursor adds custom agent orchestration.",
    },
    kind: "updated",
    confidence: "verified",
  },
];

export const FOLLOWING: FollowItem[] = [
  {
    entityId: "e-gpt",
    intensity: "instant",
    addedAt: "2026-05-01",
    reason: { zh: "日常工作深度使用", en: "Daily driver for work" },
  },
  {
    entityId: "e-claude",
    intensity: "instant",
    addedAt: "2026-05-01",
    reason: { zh: "长文档写作与代码", en: "Long docs & coding" },
  },
  {
    entityId: "e-deepseek",
    intensity: "digest",
    addedAt: "2026-06-01",
    reason: { zh: "关注开源与成本", en: "Tracking open-source & cost" },
  },
  {
    entityId: "e-mcp",
    intensity: "digest",
    addedAt: "2026-06-08",
    reason: { zh: "Agent 协议标准", en: "Agent protocol standard" },
  },
  {
    entityId: "e-cursor",
    intensity: "silent",
    addedAt: "2026-06-10",
    reason: { zh: "偶尔关注新版本", en: "Occasional updates" },
  },
];

export const findEntity = (id: string) => ENTITIES.find((e) => e.id === id);
export const findEntityBySlug = (slug: string) => ENTITIES.find((e) => e.slug === slug);
export const findSource = (id: string) => SOURCES.find((s) => s.id === id);
