/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminReviewDemoRouteImport } from './routes/admin.review-demo'
import { Route as ResearchIdRouteImport } from './routes/research.$id'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as KnowledgeModelSlugRouteImport } from './routes/knowledge.model.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review',
  path: '/admin/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewDemoRoute = AdminReviewDemoRouteImport.update({
  id: '/admin/review-demo',
  path: '/admin/review-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/research/$id',
  path: '/research/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeModelSlugRoute = KnowledgeModelSlugRouteImport.update({
  id: '/model/$slug',
  path: '/model/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ask': typeof AskRoute
  '/compare': typeof CompareRoute
  '/following': typeof FollowingRoute
  '/graph': typeof GraphRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/review-demo': typeof AdminReviewDemoRoute
  '/research/$id': typeof ResearchIdRoute
  '/share/$id': typeof ShareIdRoute
  '/knowledge/model/$slug': typeof KnowledgeModelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ask': typeof AskRoute
  '/compare': typeof CompareRoute
  '/following': typeof FollowingRoute
  '/graph': typeof GraphRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/review-demo': typeof AdminReviewDemoRoute
  '/research/$id': typeof ResearchIdRoute
  '/share/$id': typeof ShareIdRoute
  '/knowledge/model/$slug': typeof KnowledgeModelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ask': typeof AskRoute
  '/compare': typeof CompareRoute
  '/following': typeof FollowingRoute
  '/graph': typeof GraphRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/review-demo': typeof AdminReviewDemoRoute
  '/research/$id': typeof ResearchIdRoute
  '/share/$id': typeof ShareIdRoute
  '/knowledge/model/$slug': typeof KnowledgeModelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ask'
    | '/compare'
    | '/following'
    | '/graph'
    | '/knowledge'
    | '/onboarding'
    | '/admin/review'
    | '/admin/review-demo'
    | '/research/$id'
    | '/share/$id'
    | '/knowledge/model/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ask'
    | '/compare'
    | '/following'
    | '/graph'
    | '/knowledge'
    | '/onboarding'
    | '/admin/review'
    | '/admin/review-demo'
    | '/research/$id'
    | '/share/$id'
    | '/knowledge/model/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ask'
    | '/compare'
    | '/following'
    | '/graph'
    | '/knowledge'
    | '/onboarding'
    | '/admin/review'
    | '/admin/review-demo'
    | '/research/$id'
    | '/share/$id'
    | '/knowledge/model/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AskRoute: typeof AskRoute
  CompareRoute: typeof CompareRoute
  FollowingRoute: typeof FollowingRoute
  GraphRoute: typeof GraphRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminReviewDemoRoute: typeof AdminReviewDemoRoute
  ResearchIdRoute: typeof ResearchIdRoute
  ShareIdRoute: typeof ShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review-demo': {
      id: '/admin/review-demo'
      path: '/admin/review-demo'
      fullPath: '/admin/review-demo'
      preLoaderRoute: typeof AdminReviewDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$id': {
      id: '/research/$id'
      path: '/research/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/model/$slug': {
      id: '/knowledge/model/$slug'
      path: '/model/$slug'
      fullPath: '/knowledge/model/$slug'
      preLoaderRoute: typeof KnowledgeModelSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
  }
}

interface KnowledgeRouteChildren {
  KnowledgeModelSlugRoute: typeof KnowledgeModelSlugRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeModelSlugRoute: KnowledgeModelSlugRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AskRoute: AskRoute,
  CompareRoute: CompareRoute,
  FollowingRoute: FollowingRoute,
  GraphRoute: GraphRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminReviewDemoRoute: AdminReviewDemoRoute,
  ResearchIdRoute: ResearchIdRoute,
  ShareIdRoute: ShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
